app = "tunnel-deployment"

[build]
  image = "registry.fly.io/tunnel-deployment"

[env]
  TUNNEL_BASENAME = "t.agartner.com"
  TUNNEL_PORT = "443"
  SIMPLECERT_CACHE_DIR = "/certs"
  SIMPLECERT_SSL_EMAIL = "letsencrypt@agartner.com"
  SIMPLECERT_DNS_PROVIDER = "cloudflare"
  SIMPLECERT_USE_PUBLIC_DNS = "true"

[[mounts]]
  source = "tunnel_deployment_certs"
  destination = "/certs"

[[services]]
  internal_port = 443
  protocol = "tcp"

  [[services.ports]]
    port = "443"

[services.concurrency]
  hard_limit = 999999
  soft_limit = 999999